C:\Users\Kildea\Desktop\pngcrush_1_8_11_w64.exe -ow -rem allb -reduce ball.png
C:\Users\Kildea\Desktop\pngcrush_1_8_11_w64.exe -ow -rem allb -reduce compass.png
C:\Users\Kildea\Desktop\pngcrush_1_8_11_w64.exe -ow -rem allb -reduce courseselect.png
C:\Users\Kildea\Desktop\pngcrush_1_8_11_w64.exe -ow -rem allb -reduce direction_arrow.png
C:\Users\Kildea\Desktop\pngcrush_1_8_11_w64.exe -ow -rem allb -reduce pb_full.png
C:\Users\Kildea\Desktop\pngcrush_1_8_11_w64.exe -ow -rem allb -reduce pgico.png
C:\Users\Kildea\Desktop\pngcrush_1_8_11_w64.exe -ow -rem allb -reduce springmeadows.png
C:\Users\Kildea\Desktop\pngcrush_1_8_11_w64.exe -ow -rem allb -reduce springmeadows2.png
C:\Users\Kildea\Desktop\pngcrush_1_8_11_w64.exe -ow -rem allb -reduce startbutton.png
C:\Users\Kildea\Desktop\pngcrush_1_8_11_w64.exe -ow -rem allb -reduce tick.png
C:\Users\Kildea\Desktop\pngcrush_1_8_11_w64.exe -ow -rem allb -reduce tick2.png
C:\Users\Kildea\Desktop\pngcrush_1_8_11_w64.exe -ow -rem allb -reduce Title.png
C:\Users\Kildea\Desktop\pngcrush_1_8_11_w64.exe -ow -rem allb -reduce Flag.png
C:\Users\Kildea\Desktop\pngcrush_1_8_11_w64.exe -ow -rem allb -reduce Hole.png